version: '3.9'

services:

  parser:
    build: ./yandexParser
    container_name: parser
    volumes:
      - ./data/response/:/response
      - ./yandexParser:/app #Только во время разработки

    depends_on:
      - db
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}

#    networks:
#      - app_network

  db:
    image: postgres:latest
    container_name: databasePG
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/database:/var/lib/postgresql/data
      - ./data/postgres_preparations/init.sql:/docker-entrypoint-initdb.d/init.sql
#    networks:
#      - app_network


#networks:
#  app_network:
#    name: app_network
#    driver: bridge
